import { Checkpoint, CheckpointCategory, CategoryMeta, UserLocation } from './types';

export const CATEGORY_CONFIG: Record<CheckpointCategory, CategoryMeta> = {
  traffic_discipline: {
    label: 'กวดขันวินัยจราจร (หมวก/ใบขับขี่)',
    shortLabel: 'หมวก/ใบขับขี่',
    iconName: 'ShieldAlert',
    color: '#2563eb',
    badgeBg: 'bg-blue-950/60 text-blue-300 border-blue-500/40',
    badgeText: 'text-blue-300',
    description: 'ตรวจหมวกกันน็อค ใบอนุญาตขับขี่ คาดเข็มขัดนิรภัย อุปกรณ์ส่วนควบ',
    safetyAdvice: 'สวมหมวกกันน็อคทั้งคนขับคนซ้อน คาดเข็มขัดนิรภัย และพกพาใบอนุญาตขับขี่',
  },
  alcohol: {
    label: 'ตรวจวัดแอลกอฮอล์ (เป่า)',
    shortLabel: 'วัดแอลกอฮอล์',
    iconName: 'Wine',
    color: '#d97706',
    badgeBg: 'bg-amber-950/60 text-amber-300 border-amber-500/40',
    badgeText: 'text-amber-300',
    description: 'ตรวจวัดระดับแอลกอฮอล์ในลมหายใจ ชะลอความเร็วและเปิดไฟส่องสว่างในรถ',
    safetyAdvice: 'เมาไม่ขับ ปลอดภัยต่อตนเองและเพื่อนร่วมทาง หากดื่มแอลกอฮอล์ควรใช้รถสาธารณะ',
  },
  speed: {
    label: 'ตรวจจับความเร็ว / กล้องถาวร',
    shortLabel: 'จับความเร็ว',
    iconName: 'Gauge',
    color: '#dc2626',
    badgeBg: 'bg-red-950/60 text-red-300 border-red-500/40',
    badgeText: 'text-red-300',
    description: 'กล้องตรวจจับความเร็วอัตโนมัติและจุดกวดขันความเร็วเกินกำหนด',
    safetyAdvice: 'ควบคุมความเร็วให้อยู่ในเกณฑ์ที่กฎหมายกำหนด เว้นระยะห่างจากคันหน้าอย่างปลอดภัย',
  },
  smoke: {
    label: 'ตรวจวัดควันดำและมลพิษ',
    shortLabel: 'ตรวจควันดำ',
    iconName: 'Wind',
    color: '#4b5563',
    badgeBg: 'bg-stone-900/80 text-stone-300 border-stone-600',
    badgeText: 'text-stone-300',
    description: 'ตรวจวัดไอเสียและควันดำเกินมาตรฐานของยานพาหนะ',
    safetyAdvice: 'หมั่นเปลี่ยนถ่ายน้ำมันเครื่องและตรวจสภาพระบบเผาไหม้เพื่อสุขอนามัยชุมชน',
  },
  security: {
    label: 'จุดตรวจความมั่นคง / ความปลอดภัย',
    shortLabel: 'ตรวจความมั่นคง',
    iconName: 'ShieldCheck',
    color: '#7c3aed',
    badgeBg: 'bg-purple-950/60 text-purple-300 border-purple-500/40',
    badgeText: 'text-purple-300',
    description: 'ตรวจค้นสิ่งผิดกฎหมาย ป้องปรามเหตุอาชญากรรม',
    safetyAdvice: 'ให้ความร่วมมือในการตรวจ ชะลอรถและเปิดกระจกลงเพื่อความสะดวกของเจ้าหน้าที่',
  },
};

export const DEFAULT_USER_LOCATION: UserLocation = {
  lat: 13.7650,
  lng: 100.5383,
  accuracy: 15,
};

// ฐานข้อมูลพิกัดจุดตรวจจริงยอดฮิตและกล้องตรวจจับความเร็วถาวรในกรุงเทพฯ
export const INITIAL_CHECKPOINTS: Checkpoint[] = [
  {
    id: 'cp-1',
    title: 'ถ.วิภาวดีรังสิต ขาเข้า (หน้า รร.สุรศักดิ์มนตรี)',
    locationName: 'ถนนวิภาวดีรังสิต ขาเข้า คู่ขนาน',
    lat: 13.7745,
    lng: 100.5567,
    category: 'traffic_discipline',
    direction: 'inbound',
    directionText: 'ขาเข้ามุ่งหน้าดินแดง',
    note: 'เลนคู่ขนานซ้ายสุด กวดขันสวมหมวกกันน็อคและป้ายทะเบียน',
    reportedTimestamp: Date.now() - 1000 * 60 * 12,
    reportedBy: 'สายตรวจกทม.',
    upvotes: 19,
    downvotes: 1,
    status: 'active',
  },
  {
    id: 'cp-2',
    title: 'ถ.พหลโยธิน ขาออก (หน้าเมเจอร์ รัชโยธิน)',
    locationName: 'แยกเสนานิคม - รัชโยธิน',
    lat: 13.8298,
    lng: 100.5702,
    category: 'traffic_discipline',
    direction: 'outbound',
    directionText: 'ขาออกมุ่งหน้าเกษตร',
    note: 'ด่านตรวจวินัยจราจรและช่องทางจักรยานยนต์',
    reportedTimestamp: Date.now() - 1000 * 60 * 25,
    reportedBy: 'ไรเดอร์รัชโยธิน',
    upvotes: 24,
    downvotes: 0,
    status: 'active',
  },
  {
    id: 'cp-3',
    title: 'ถ.พระราม 9 มุ่งหน้าศรีนครินทร์ (ใต้สะพานข้ามแยกราม)',
    locationName: 'พระราม 9 มุ่งหน้าศรีนครินทร์',
    lat: 13.7486,
    lng: 100.5891,
    category: 'alcohol',
    direction: 'outbound',
    directionText: 'ขาออกมุ่งหน้ามอเตอร์เวย์',
    note: 'ตั้งกรวยบีบเหลือ 2 เลนขวา มีการตรวจวัดแอลกอฮอล์ช่วงดึก',
    reportedTimestamp: Date.now() - 1000 * 60 * 38,
    reportedBy: 'เพื่อนร่วมทางBKK',
    upvotes: 35,
    downvotes: 2,
    status: 'active',
  },
  {
    id: 'cp-4',
    title: 'ถ.รัชดาภิเษก (หน้าศาลอาญา รัชดา 36)',
    locationName: 'รัชดาภิเษก มุ่งหน้าพระราม 9',
    lat: 13.8185,
    lng: 100.5772,
    category: 'alcohol',
    direction: 'inbound',
    directionText: 'ขาเข้ามุ่งหน้าแยกรัชโยธิน-สุทธิสาร',
    note: 'จุดตั้งด่านตรวจวัดแอลกอฮอล์และกวดขันวินัยจราจรยอดฮิต',
    reportedTimestamp: Date.now() - 1000 * 60 * 18,
    reportedBy: 'พี่ตั้มสายตรวจ',
    upvotes: 28,
    downvotes: 1,
    status: 'active',
  },
  {
    id: 'cp-5',
    title: 'ดอนเมืองโทลล์เวย์ (กล้องตรวจจับความเร็วถาวร กม. 14)',
    locationName: 'ทางยกระดับอุตราภิมุข ขาออก ช่วงดอนเมือง',
    lat: 13.8982,
    lng: 100.5968,
    category: 'speed',
    direction: 'outbound',
    directionText: 'ขาออกมุ่งหน้ารังสิต',
    note: 'กล้องตรวจจับความเร็วถาวร จำกัดความเร็วไม่เกิน 80-90 กม./ชม.',
    reportedTimestamp: Date.now() - 1000 * 60 * 60 * 2,
    reportedBy: 'ระบบกล้องทางหลวง',
    upvotes: 45,
    downvotes: 0,
    status: 'active',
  },
  {
    id: 'cp-6',
    title: 'ถ.เกษตร-นวมินทร์ (ประเสริฐมนูกิจ ช่วงตอม่อ 125)',
    locationName: 'ถนนประเสริฐมนูกิจ มุ่งหน้าเกษตร',
    lat: 13.8322,
    lng: 100.6125,
    category: 'alcohol',
    direction: 'inbound',
    directionText: 'ขาเข้ามุ่งหน้าแยกเกษตร',
    note: 'จุดตรวจความพร้อมผู้ขับขี่และวัดระดับแอลกอฮอล์',
    reportedTimestamp: Date.now() - 1000 * 60 * 45,
    reportedBy: 'ไรเดอร์นวมินทร์',
    upvotes: 16,
    downvotes: 3,
    status: 'active',
  },
  {
    id: 'cp-7',
    title: 'ถ.บรมราชชนนี ขาเข้า (ช่วงสายใต้เก่า ตลิ่งชัน)',
    locationName: 'บรมราชชนนี ทางคู่ขนาน',
    lat: 13.7820,
    lng: 100.4721,
    category: 'smoke',
    direction: 'inbound',
    directionText: 'ขาเข้ามุ่งหน้าสะพานสมเด็จพระปิ่นเกล้า',
    note: 'จุดตรวจมลพิษควันดำและตรวจสภาพรถบรรทุก/กระบะ',
    reportedTimestamp: Date.now() - 1000 * 60 * 95,
    reportedBy: 'ลุงขับสองแถว',
    upvotes: 18,
    downvotes: 4,
    status: 'unverified',
  },
  {
    id: 'cp-8',
    title: 'ถ.ราชพฤกษ์ (ช่วงวงเวียนพระราม 5 มุ่งหน้าสาทร)',
    locationName: 'ราชพฤกษ์ มุ่งหน้ากรุงเทพฯ',
    lat: 13.8214,
    lng: 100.4502,
    category: 'traffic_discipline',
    direction: 'inbound',
    directionText: 'ขาเข้ามุ่งหน้าเพชรเกษม-สาทร',
    note: 'ตรวจจับช่องทางห้าม จยย. และกวดขันป้ายทะเบียน',
    reportedTimestamp: Date.now() - 1000 * 60 * 50,
    reportedBy: 'คนฝั่งธน',
    upvotes: 22,
    downvotes: 2,
    status: 'active',
  },
  {
    id: 'cp-9',
    title: 'มอเตอร์เวย์ สาย 7 (กล้องตรวจจับความเร็ว กม. 12)',
    locationName: 'มอเตอร์เวย์ กรุงเทพ - ชลบุรี สายใหม่',
    lat: 13.7291,
    lng: 100.7382,
    category: 'speed',
    direction: 'both',
    directionText: 'ทั้งสองทิศทาง ขาเข้าและขาออก',
    note: 'กล้องตรวจจับความเร็วอัตโนมัติ 24 ชม. ควบคุมความเร็ว 120 กม./ชม.',
    reportedTimestamp: Date.now() - 1000 * 60 * 60 * 4,
    reportedBy: 'ระบบกล้องทางหลวง',
    upvotes: 52,
    downvotes: 0,
    status: 'active',
  },
  {
    id: 'cp-10',
    title: 'ถ.สาทรใต้ (หน้า BTS สุรศักดิ์)',
    locationName: 'สาทรใต้ เลนซ้าย',
    lat: 13.7192,
    lng: 100.5215,
    category: 'security',
    direction: 'outbound',
    directionText: 'ขาออกมุ่งหน้าฝั่งธนบุรี',
    note: 'ตรวจตราความปลอดภัยและกวดขันรถจักรยานยนต์',
    reportedTimestamp: Date.now() - 1000 * 60 * 110,
    reportedBy: 'SathornRider',
    upvotes: 11,
    downvotes: 5,
    status: 'unverified',
  },
  {
    id: 'cp-11',
    title: 'ถ.สุขุมวิท 21 (อโศกมนตรี หน้าตึกเสริมมิตร)',
    locationName: 'อโศกมนตรี มุ่งหน้าเพชรบุรี',
    lat: 13.7423,
    lng: 100.5607,
    category: 'speed',
    direction: 'both',
    directionText: 'ทั้งสองทิศทาง',
    note: 'กวดขันการกลับรถในที่ห้าม และกวดขันวินัยจราจรช่วงเย็น',
    reportedTimestamp: Date.now() - 1000 * 60 * 65,
    reportedBy: 'หนุ่มออฟฟิศอโศก',
    upvotes: 7,
    downvotes: 1,
    status: 'unverified',
  },
  {
    id: 'cp-12',
    title: 'ถ.พระราม 2 ขาออก (หน้าเซ็นทรัล พระราม 2)',
    locationName: 'พระราม 2 ทางด่วนช่องหลัก',
    lat: 13.6672,
    lng: 100.4375,
    category: 'speed',
    direction: 'outbound',
    directionText: 'ขาออกมุ่งหน้าสมุทรสาคร',
    note: 'จุดตรวจจับความเร็วยานพาหนะและกวดขันรถบรรทุกวิ่งขวา',
    reportedTimestamp: Date.now() - 1000 * 60 * 75,
    reportedBy: 'เพื่อนร่วมทางมหาชัย',
    upvotes: 19,
    downvotes: 3,
    status: 'active',
  },
  {
    id: 'cp-13',
    title: 'ถ.สุขุมวิท 55 (ปากซอยทองหล่อ หน้าสถานี BTS)',
    locationName: 'ทองหล่อ สุขุมวิท 55',
    lat: 13.7258,
    lng: 100.5794,
    category: 'alcohol',
    direction: 'inbound',
    directionText: 'มุ่งหน้าถนนสุขุมวิทสายหลัก',
    note: 'จุดตรวจวัดระดับแอลกอฮอล์ช่วงดึก ชะลอความเร็วและเปิดกระจก',
    reportedTimestamp: Date.now() - 1000 * 60 * 15,
    reportedBy: 'สายปาร์ตี้กลับบ้านปลอดภัย',
    upvotes: 31,
    downvotes: 1,
    status: 'active',
  },
  {
    id: 'cp-14',
    title: 'ถ.สุขุมวิท 63 (เอกมัย มุ่งหน้าเพชรบุรีตัดใหม่)',
    locationName: 'ถนนเอกมัย ช่วงบิ๊กซีเอกมัย',
    lat: 13.7312,
    lng: 100.5865,
    category: 'traffic_discipline',
    direction: 'outbound',
    directionText: 'มุ่งหน้าแยกคลองตัน',
    note: 'กวดขันวินัยจราจร ตรวจสวมหมวกกันน็อคและใบขับขี่',
    reportedTimestamp: Date.now() - 1000 * 60 * 30,
    reportedBy: 'ไรเดอร์เอกมัย',
    upvotes: 15,
    downvotes: 0,
    status: 'active',
  },
  {
    id: 'cp-15',
    title: 'ถ.เพชรบุรีตัดใหม่ (ใต้ทางด่วนเพชรบุรี มุ่งหน้าคลองตัน)',
    locationName: 'เพชรบุรีตัดใหม่ ใต้สะพานทางด่วน',
    lat: 13.7485,
    lng: 100.5695,
    category: 'traffic_discipline',
    direction: 'outbound',
    directionText: 'มุ่งหน้าอาร์ซีเอ-คลองตัน',
    note: 'กวดขันวินัยจราจร ช่องทางห้าม จยย. และป้ายทะเบียน',
    reportedTimestamp: Date.now() - 1000 * 60 * 40,
    reportedBy: 'คนทำงานอโศก',
    upvotes: 21,
    downvotes: 2,
    status: 'active',
  },
  {
    id: 'cp-16',
    title: 'สะพานภูมิพล 1-2 (กล้องตรวจจับความเร็วถาวร)',
    locationName: 'สะพานภูมิพล ข้ามแม่น้ำเจ้าพระยา',
    lat: 13.6654,
    lng: 100.5401,
    category: 'speed',
    direction: 'both',
    directionText: 'ทั้งสองทิศทาง ข้ามแม่น้ำเจ้าพระยา',
    note: 'กล้องตรวจจับความเร็ว 24 ชม. จำกัดความเร็ว 60-80 กม./ชม. ห้าม จยย. ขึ้นสะพาน',
    reportedTimestamp: Date.now() - 1000 * 60 * 60 * 5,
    reportedBy: 'ระบบกล้องจราจร',
    upvotes: 68,
    downvotes: 0,
    status: 'active',
  },
  {
    id: 'cp-17',
    title: 'สะพานพระราม 8 (ทางลงฝั่งพระนคร แยกวิสุทธิกษัตริย์)',
    locationName: 'เชิงสะพานพระราม 8 มุ่งหน้าราชดำเนิน',
    lat: 13.7689,
    lng: 100.4988,
    category: 'traffic_discipline',
    direction: 'inbound',
    directionText: 'มุ่งหน้าแยกวิสุทธิกษัตริย์',
    note: 'กวดขันหมวกกันน็อคและอุปกรณ์ส่วนควบเลนซ้าย',
    reportedTimestamp: Date.now() - 1000 * 60 * 55,
    reportedBy: 'เด็กฝั่งธนข้ามสะพาน',
    upvotes: 27,
    downvotes: 1,
    status: 'active',
  },
  {
    id: 'cp-18',
    title: 'ถ.บางนา-ตราด กม. 4.5 (หน้าเซ็นทรัลบางนา คู่ขนาน)',
    locationName: 'ถนนบางนา-ตราด ขาออก กม.4',
    lat: 13.6678,
    lng: 100.6345,
    category: 'smoke',
    direction: 'outbound',
    directionText: 'ขาออกมุ่งหน้าบางพลี ชลบุรี',
    note: 'จุดตรวจวัดมลพิษควันดำและตรวจสภาพรถกระบะ/บรรทุก',
    reportedTimestamp: Date.now() - 1000 * 60 * 80,
    reportedBy: 'สายส่งของบางนา',
    upvotes: 14,
    downvotes: 2,
    status: 'active',
  },
  {
    id: 'cp-19',
    title: 'ทางหลวงพิเศษหมายเลข 9 M9 (วงแหวนกาญจนาภิเษก ทับช้าง)',
    locationName: 'ถนนกาญจนาภิเษก วงแหวนรอบนอกตะวันออก',
    lat: 13.7431,
    lng: 100.7023,
    category: 'speed',
    direction: 'both',
    directionText: 'ทั้งสองทิศทาง ช่วงก่อนถึงด่านเก็บเงิน',
    note: 'กล้องตรวจจับความเร็วอัตโนมัติ ควบคุมความเร็วไม่เกิน 120 กม./ชม.',
    reportedTimestamp: Date.now() - 1000 * 60 * 60 * 3,
    reportedBy: 'ระบบกล้องทางหลวง',
    upvotes: 43,
    downvotes: 0,
    status: 'active',
  },
  {
    id: 'cp-20',
    title: 'ทางพิเศษศรีรัช (ช่วงต่างระดับพญาไท มุ่งหน้าแจ้งวัฒนะ)',
    locationName: 'ทางพิเศษศรีรัช ขาออก',
    lat: 13.7663,
    lng: 100.5287,
    category: 'speed',
    direction: 'outbound',
    directionText: 'ขาออกมุ่งหน้างามวงศ์วาน แจ้งวัฒนะ',
    note: 'กล้องตรวจจับความเร็วบนทางด่วน จำกัดความเร็ว 90-110 กม./ชม.',
    reportedTimestamp: Date.now() - 1000 * 60 * 60 * 6,
    reportedBy: 'ระบบตรวจจับความเร็ว กทพ.',
    upvotes: 39,
    downvotes: 0,
    status: 'active',
  },
  {
    id: 'cp-21',
    title: 'ถ.รามอินทรา กม. 8 (ใต้ทางด่วนฉลองรัช ขาออก)',
    locationName: 'ถนนรามอินทรา ช่วง กม.8 มุ่งหน้ามีนบุรี',
    lat: 13.8291,
    lng: 100.6482,
    category: 'alcohol',
    direction: 'outbound',
    directionText: 'ขาออกมุ่งหน้ามีนบุรี',
    note: 'จุดตรวจความพร้อมผู้ขับขี่และวัดแอลกอฮอล์ช่วงหลังเที่ยงคืน',
    reportedTimestamp: Date.now() - 1000 * 60 * 20,
    reportedBy: 'ไรเดอร์รามอินทรา',
    upvotes: 22,
    downvotes: 1,
    status: 'active',
  },
  {
    id: 'cp-22',
    title: 'ถ.พระราม 3 (ใต้สะพานภูมิพล มุ่งหน้าคลองเตย)',
    locationName: 'ถนนพระราม 3 เลนคู่ขนาน',
    lat: 13.6821,
    lng: 100.5342,
    category: 'traffic_discipline',
    direction: 'inbound',
    directionText: 'มุ่งหน้าแยกคลองเตย',
    note: 'กวดขันวินัยจราจร การขับขี่เร็ว และตรวจอุปกรณ์ส่วนควบรถ',
    reportedTimestamp: Date.now() - 1000 * 60 * 65,
    reportedBy: 'คนพื้นที่พระราม3',
    upvotes: 17,
    downvotes: 3,
    status: 'active',
  },
  {
    id: 'cp-23',
    title: 'ถ.งามวงศ์วาน (หน้าเดอะมอลล์งามวงศ์วาน ขาออก)',
    locationName: 'ถนนงามวงศ์วาน มุ่งหน้าแคราย',
    lat: 13.8592,
    lng: 100.5421,
    category: 'traffic_discipline',
    direction: 'outbound',
    directionText: 'มุ่งหน้าแยกแคราย นนทบุรี',
    note: 'กวดขันหมวกกันน็อคและห้ามปาดเข้าเส้นทึบหน้าห้าง',
    reportedTimestamp: Date.now() - 1000 * 60 * 35,
    reportedBy: 'เด็กมอเกษตร',
    upvotes: 25,
    downvotes: 2,
    status: 'active',
  },
  {
    id: 'cp-24',
    title: 'ทางพิเศษบูรพาวิถี (บางนา-ชลบุรี ช่วง กม. 19)',
    locationName: 'ทางยกระดับบูรพาวิถี ขาออก',
    lat: 13.6125,
    lng: 100.7712,
    category: 'speed',
    direction: 'outbound',
    directionText: 'มุ่งหน้าสนามบินสุวรรณภูมิและชลบุรี',
    note: 'กล้องตรวจจับความเร็วถาวร จำกัดความเร็วไม่เกิน 110 กม./ชม.',
    reportedTimestamp: Date.now() - 1000 * 60 * 60 * 8,
    reportedBy: 'ระบบกล้องทางด่วนบูรพาวิถี',
    upvotes: 56,
    downvotes: 0,
    status: 'active',
  },
  {
    id: 'cp-25',
    title: 'ถ.ลาดพร้าว (หน้าอิมพีเรียล ลาดพร้าว 81)',
    locationName: 'ถนนลาดพร้าว มุ่งหน้าบางกะปิ',
    lat: 13.7912,
    lng: 100.5978,
    category: 'security',
    direction: 'outbound',
    directionText: 'มุ่งหน้าแยกบางกะปิ',
    note: 'จุดตรวจความปลอดภัยและป้องปรามเหตุ ตรวจค้นสิ่งผิดกฎหมาย',
    reportedTimestamp: Date.now() - 1000 * 60 * 48,
    reportedBy: 'วินลาดพร้าว',
    upvotes: 18,
    downvotes: 1,
    status: 'active',
  },
];

export function calculateDistanceKm(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return parseFloat((R * c).toFixed(1));
}

export function formatTimeAgo(timestamp: number): string {
  const diffMs = Date.now() - timestamp;
  const diffMinutes = Math.floor(diffMs / (1000 * 60));

  if (diffMinutes < 1) return 'เมื่อสักครู่';
  if (diffMinutes < 60) return `${diffMinutes} นาทีที่แล้ว`;
  const diffHours = Math.floor(diffMinutes / 60);
  if (diffHours < 24) return `${diffHours} ชั่วโมงที่แล้ว`;
  return `${Math.floor(diffHours / 24)} วันที่แล้ว`;
}
